### ISSUE TITLE
Consistent filenames for lists

### ISSUE THREAD

**Issue by klauswyser** [EC-Earth/cmor-metadata-fixer#2]
Suggestion: shouldn't we use ``list-of-modified-files-1.txt`` instead of ``list-of-modified-files.txt`` to make it more consistent with the other filenames?

https://github.com/EC-Earth/cmor-metadata-fixer/blob/c68b5abfac988aa094a93fd9bf0869ba3b421ba3/cmorMDfixer-safe-mode-wrapper.sh#L22-L25

**Comment by klauswyser** [comment]
Pinging @treerink

**Comment by treerink** [comment]
Yes that's ok, I will change that
